# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171224_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupp',
            new_name='patient_info',
        ),
    ]
