# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171224_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('Chamber_address', models.TextField()),
                ('Speciality', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=100)),
            ],
        ),
    ]
